<?php
/**
 * @file
 * Code for the Commerce Marketplace Reviews feature.
 */

include_once 'ogmk_reviews.features.inc';

/**
 * Hooks.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ogmk_reviews_form_review_node_form_alter(&$form, &$form_state, $form_id) {
  // The "product" node will be fetched from the line item and will be set when
  // the "review" node will be saved.
  $form['ogmk_node_product_ref']['#access'] = FALSE;

  // Action buttons improvements.
  $form['actions']['submit']['#value'] = t('Submit');
  $form['actions']['submit']['#attributes']['class'][] = 'fa fa-check';

  /**
   * @Issue(
   *   "Disallow adding a review for a line item that already has one"
   *   type="bug"
   *   priority="normal"
   * )
   * @Issue(
   *   "Add an info alert with information about how to make a review"
   *   type="improvement"
   *   priority="low"
   * )
   * @Issue(
   *   "Test if OG permissions properly work, preventing to add a review to a
   *   line item/shop that shouldn't be possible"
   *   type="bug"
   *   priority="normal"
   *   labels="security, testing"
   * )
   * @Issue(
   *   "Improve the stars rating appearance and remove/hide the dropdown"
   *   type="bug"
   *   priority="normal"
   *   labels="ux"
   * )
   * @Issue(
   *   "Move the action buttons to the right and separate them from the main
   *   form"
   *   type="bug"
   *   priority="normal"
   *   labels="ux"
   * )
   * @Issue(
   *   "Populate the 'ogmk_node_product_ref' field when the node is saved"
   *   type="bug"
   *   priority="normal"
   *   labels="data"
   * )
   */
}
